function response = breebaart2001centralproc_AMT_call(pathway_out)

response = breebaart2001centralproc({pathway_out{1}.ei, pathway_out{2}.ei, pathway_out{3}.ei},...
    {pathway_out{1}.left,pathway_out{2}.left,pathway_out{3}.left},...
    {pathway_out{1}.right,pathway_out{2}.right,pathway_out{3}.right},'lbr');